sudo: false

language: node_js
node_js:
  - 8
  - 10

script:
  - npm run coverage -- --no-cache --runInBand

after_success:
  - npm run coverage:report

deploy:
  provider: script
  script: npm --prefix docs ci && CI=0 npm --prefix docs run deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|new-docs$
