sudo: false

language: node_js
node_js:
  - 8
  - 10

script:
  - npm run coverage -- --no-cache --runInBand

after_success:
  - npm run coverage:report

before_deploy:
  - CI=0 npm --prefix docs run build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local-dir: docs/.docz/dist
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|v2$
